import { StudyMaterial } from './types/learnverse'

export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: 'bio-101',
    title: 'Cellular Respiration & ATP Synthesis',
    subject: 'Biology / Biochemistry',
    subjectColor: 'from-emerald-500/20 to-green-500/10 text-emerald-400 border-emerald-500/30',
    type: 'pdf',
    sourceFileName: 'Cellular_Bio_Chapter_7_Metabolism.pdf',
    uploadDate: 'Today at 10:45 AM',
    estimatedStudyTimeMinutes: 12,
    progressPercentage: 68,
    summaryNotes: {
      title: 'Cellular Respiration Breakdown',
      readingTimeMinutes: 4,
      keyTakeaways: [
        'Cellular respiration converts biochemical energy from nutrients into ATP through 4 stages.',
        'Glycolysis is anaerobic and occurs in the cytoplasm, producing a net 2 ATP and 2 NADH.',
        'The Citric Acid (Krebs) Cycle occurs inside the mitochondrial matrix, generating high-energy electron carriers.',
        'Oxidative Phosphorylation (ETC + Chemiosmosis) generates the bulk of ATP (~28-32 ATP) via ATP synthase driven by a proton gradient.',
      ],
      keyTerms: [
        {
          term: 'ATP (Adenosine Triphosphate)',
          definition: 'The primary energy currency of the cell, storing energy in high-energy phosphate bonds.',
          importance: 'high',
        },
        {
          term: 'Chemiosmosis',
          definition: 'The movement of hydrogen ions (protons) across a semipermeable membrane down their electrochemical gradient to power ATP synthase.',
          importance: 'high',
        },
        {
          term: 'NADH / FADH2',
          definition: 'Reduced coenzymes that act as electron shuttles carrying high-energy electrons to the electron transport chain.',
          importance: 'medium',
        },
        {
          term: 'Substrate-Level Phosphorylation',
          definition: 'Direct transfer of a phosphate group to ADP from an intermediate metabolic substrate, seen in glycolysis and Krebs cycle.',
          importance: 'medium',
        },
      ],
      sections: [
        {
          heading: '1. Glycolysis: The Starting Engine',
          summary: 'The initial 10-step metabolic pathway converting 1 glucose molecule into 2 pyruvate molecules.',
          bulletPoints: [
            'Energy Investment Phase: Consumes 2 ATP to phosphorylate glucose.',
            'Energy Payoff Phase: Produces 4 ATP and 2 NADH.',
            'Net Yield: 2 ATP + 2 NADH + 2 Pyruvate.',
            'Oxygen Independent: Operates under both aerobic and anaerobic conditions.',
          ],
          keyTakeaway: 'Occurs entirely in the cytosol without requiring mitochondrial membranes or oxygen.',
        },
        {
          heading: '2. Pyruvate Oxidation & Citric Acid Cycle',
          summary: 'Pyruvate enters mitochondria and is oxidized into Acetyl-CoA, which fuels the cyclic reaction series.',
          bulletPoints: [
            'Pyruvate Dehydrogenase complex removes CO2 and generates 1 NADH per pyruvate.',
            'Acetyl-CoA combines with 4-carbon Oxaloacetate to form 6-carbon Citrate.',
            'Per glucose (2 cycles): Produces 6 NADH, 2 FADH2, 2 ATP (or GTP), and releases 4 CO2.',
          ],
          keyTakeaway: 'Maximizes harvesting of high-energy electrons stored in NADH and FADH2.',
        },
        {
          heading: '3. Oxidative Phosphorylation & ATP Synthase',
          summary: 'Electrons pass through transmembrane Complexes I-IV, pumping protons into the intermembrane space.',
          bulletPoints: [
            'Oxygen acts as the terminal electron acceptor, bonding with protons to form H2O.',
            'Proton motive force drives the rotor mechanism of ATP Synthase.',
            'Yields approximately 26-28 ATP via chemiosmotic coupling.',
          ],
          keyTakeaway: 'The ultimate bottleneck: Without oxygen, the entire electron transport chain backs up.',
        },
      ],
    },
    flashcards: [
      {
        id: 'fc-1',
        topic: 'Glycolysis',
        question: 'What is the net gain of ATP and NADH per glucose molecule during glycolysis alone?',
        answer: 'Net 2 ATP and 2 NADH (4 ATP produced minus 2 ATP invested).',
        hint: 'Think about the investment vs payoff phase.',
        confidence: 'mastered' as any,
      },
      {
        id: 'fc-2',
        topic: 'Mitochondrial Transport',
        question: 'Where specifically does the Citric Acid (Krebs) cycle take place inside a eukaryotic cell?',
        answer: 'Inside the Mitochondrial Matrix.',
        hint: 'It is within the innermost compartment surrounded by the cristae.',
        confidence: 'medium',
      },
      {
        id: 'fc-3',
        topic: 'Electron Transport Chain',
        question: 'What is the final (terminal) electron acceptor in aerobic cellular respiration?',
        answer: 'Molecular Oxygen (O2), which accepts electrons and protons to form Water (H2O).',
        hint: 'It is the element you breathe in.',
        confidence: 'hard',
      },
      {
        id: 'fc-4',
        topic: 'Chemiosmosis',
        question: 'How does the proton gradient generate ATP through ATP Synthase?',
        answer: 'Protons flow down their electrochemical gradient from the intermembrane space back into the matrix, rotating the catalytic rotor head of ATP synthase to phosphorylate ADP into ATP.',
        hint: 'Think of a microscopic hydroelectric turbine.',
        confidence: 'medium',
      },
      {
        id: 'fc-5',
        topic: 'Fermentation',
        question: 'Why must cells perform fermentation in the absence of oxygen?',
        answer: 'To regenerate NAD+ from NADH so that glycolysis can continue producing ATP anaerobically.',
        hint: 'It is not about making extra ATP, but recycling a vital coenzyme.',
        confidence: 'hard',
      },
    ],
    quiz: {
      id: 'quiz-bio-101',
      title: 'Cellular Respiration Mastery Assessment',
      totalQuestions: 4,
      passingScore: 75,
      questions: [
        {
          id: 'q-1',
          topic: 'Glycolysis',
          question: 'Which of the following processes occurs in the cytosol and does NOT require oxygen?',
          options: ['Glycolysis', 'Citric Acid Cycle', 'Electron Transport Chain', 'Pyruvate Oxidation'],
          correctIndex: 0,
          explanation: 'Glycolysis is an anaerobic pathway that takes place entirely within the cytoplasm of the cell.',
        },
        {
          id: 'q-2',
          topic: 'Electron Transport Chain',
          question: 'If a poison inhibits Complex IV of the electron transport chain, what immediate effect will occur?',
          options: [
            'NADH production will increase dramatically',
            'Electron flow stops, oxygen cannot be reduced to water, and proton pumping ceases',
            'ATP Synthase will spin in reverse producing glucose',
            'Glycolysis will immediately produce double the ATP',
          ],
          correctIndex: 1,
          explanation: 'Blocking Complex IV halts the transfer of electrons to oxygen, destroying the proton gradient required for ATP synthesis.',
        },
        {
          id: 'q-3',
          topic: 'ATP Yields',
          question: 'Approximately how many ATP molecules are generated per molecule of glucose in complete aerobic respiration?',
          options: ['2 ATP', '4 ATP', '30 to 32 ATP', '100 ATP'],
          correctIndex: 2,
          explanation: 'Modern biochemical measurements calculate between 30 to 32 ATP per glucose under optimal aerobic conditions.',
        },
        {
          id: 'q-4',
          topic: 'Chemiosmosis',
          question: 'What is the immediate driving force behind ATP Synthase activity during chemiosmosis?',
          options: [
            'Direct hydrolysis of GTP',
            'Proton Electrochemical Gradient (Proton-Motive Force)',
            'Thermal expansion of mitochondrial cristae',
            'Active transport of sodium-potassium pumps',
          ],
          correctIndex: 1,
          explanation: 'The proton gradient across the inner mitochondrial membrane creates the potential energy that drives ATP Synthase rotation.',
        },
      ],
    },
    reel: {
      id: 'reel-bio-101',
      title: 'How ATP Powers Your Body in 45 Seconds',
      durationSeconds: 45,
      visualStyle: '3d-infographic',
      narrationScript: 'Every second, your trillions of cells churn through billions of ATP molecules. It starts with the glucose you eat, split in half during glycolysis. Then inside your mitochondria, an electron roller coaster pumps protons across the membrane. When those protons rush back through ATP synthase, it spins like a microscopic turbine, charging your biological batteries.',
      audioWaveform: [0.2, 0.4, 0.7, 0.9, 0.6, 0.8, 0.95, 0.7, 0.4, 0.6, 0.85, 0.9, 0.75, 0.5, 0.3, 0.6, 0.8, 1.0, 0.7, 0.4, 0.3],
      chapters: [
        { id: 'c-1', title: '01. Glucose Split', timestampSeconds: 0, subtitle: 'Glycolysis splits 6-carbon glucose into pyruvate in the cytoplasm.' },
        { id: 'c-2', title: '02. The Matrix Engine', timestampSeconds: 15, subtitle: 'Krebs Cycle extracts high-energy electrons into NADH carriers.' },
        { id: 'c-3', title: '03. Proton Turbine', timestampSeconds: 30, subtitle: 'ATP Synthase spins under proton motive force, generating 32 ATP.' },
      ],
    },
    overview: 'Cellular respiration converts biochemical energy from nutrients into ATP through glycolysis, the Krebs cycle, and oxidative phosphorylation.',
    subtopics: [
      {
        id: 'sub-bio-1',
        documentId: 'bio-101',
        title: 'Glycolysis: The Anaerobic Engine',
        description: 'Decomposes 1 glucose molecule into 2 pyruvate molecules yielding net 2 ATP and 2 NADH in the cytoplasm.',
        learningObjectives: ['Trace the 10-step glycolytic pathway', 'Calculate net ATP and NADH yields without oxygen'],
        sourceText: 'Glycolysis is the ancient metabolic pathway occurring in the cytosol...',
        estimatedDurationSeconds: 45,
        displayOrder: 1,
        reelStatus: 'ready',
        reel: {
          id: 'reel-sub-bio-1',
          title: 'Glycolysis in 45 Seconds',
          durationSeconds: 45,
          visualStyle: '3d-infographic',
          subtopicId: 'sub-bio-1',
          narrationScript: 'Welcome to Glycolysis. In the cytoplasm, one glucose molecule is cleaved into two pyruvates, netting 2 ATP and 2 NADH without requiring oxygen.',
          audioWaveform: [0.2, 0.4, 0.7, 0.9, 0.6, 0.8, 0.95, 0.7, 0.4, 0.6, 0.85, 0.9, 0.75, 0.5, 0.3],
          chapters: [
            { id: 'c-1', title: '01. Cytosolic Activation', timestampSeconds: 0, subtitle: 'Glucose phosphorylation by hexokinase.' },
            { id: 'c-2', title: '02. Energy Payoff', timestampSeconds: 15, subtitle: 'Substrate-level phosphorylation yields 4 ATP.' },
            { id: 'c-3', title: '03. Net Output', timestampSeconds: 30, subtitle: 'Net 2 ATP + 2 NADH ready for mitochondria.' },
          ],
        },
      },
      {
        id: 'sub-bio-2',
        documentId: 'bio-101',
        title: 'Pyruvate Oxidation & Krebs Cycle',
        description: 'Transfers Acetyl-CoA into the mitochondrial matrix to generate high-energy electron carriers.',
        learningObjectives: ['Understand Acetyl-CoA formation', 'Track carbon loss as CO2 and coenzyme reduction'],
        sourceText: 'Pyruvate is actively transported into the mitochondrial matrix where pyruvate dehydrogenase oxidizes it...',
        estimatedDurationSeconds: 50,
        displayOrder: 2,
        reelStatus: 'not_started',
      },
      {
        id: 'sub-bio-3',
        documentId: 'bio-101',
        title: 'Electron Transport Chain & Chemiosmosis',
        description: 'Complexes I-IV pump protons across the inner membrane to power the rotational catalytic ATP Synthase turbine.',
        learningObjectives: ['Explain the proton motive force gradient', 'Contrast oxidative vs substrate-level phosphorylation'],
        sourceText: 'Oxidative phosphorylation generates up to 28-32 ATP using the proton motive force across the cristae...',
        estimatedDurationSeconds: 48,
        displayOrder: 3,
        reelStatus: 'not_started',
      },
    ],
    knowledgeGap: {
      overallMastery: 68,
      weakestArea: 'Electron Transport Chain & Poisons',
      strongestArea: 'Glycolysis Net Yields',
      recommendedStudyOrder: ['Electron Transport Chain & Poisons', 'Chemiosmotic Coupling', 'Citric Acid Cycle Intermediates'],
      topics: [
        {
          name: 'Glycolysis Phases & Energetics',
          masteryPercentage: 92,
          status: 'mastered',
          questionsAttempted: 12,
          recommendedAction: 'Solid mastery achieved! Keep reviewed with occasional flashcards.',
        },
        {
          name: 'Citric Acid Cycle Stoichiometry',
          masteryPercentage: 70,
          status: 'improving',
          questionsAttempted: 8,
          recommendedAction: 'Review the transition from Oxaloacetate to Citrate and carbon counts.',
        },
        {
          name: 'Electron Transport Chain & Inhibitors',
          masteryPercentage: 45,
          status: 'critical-gap',
          questionsAttempted: 6,
          recommendedAction: 'Focus on Complexes I-IV sequence and how cyanide/rotenone disrupt ATP synthesis.',
        },
        {
          name: 'Chemiosmosis & Proton Gradient',
          masteryPercentage: 65,
          status: 'improving',
          questionsAttempted: 9,
          recommendedAction: 'Revisit how proton motive force couples directly to ATP Synthase rotation.',
        },
      ],
    },
  },
  {
    id: 'cs-201',
    title: 'Data Structures & Binary Tree Traversals',
    subject: 'Computer Science',
    subjectColor: 'from-cyan-500/20 to-blue-500/10 text-cyan-400 border-cyan-500/30',
    type: 'link',
    sourceUrl: 'https://ocw.mit.edu/courses/6-006-trees-algorithms',
    uploadDate: 'Yesterday at 4:15 PM',
    estimatedStudyTimeMinutes: 15,
    progressPercentage: 85,
    summaryNotes: {
      title: 'Binary Trees & Graph Traversals Summary',
      readingTimeMinutes: 5,
      keyTakeaways: [
        'Tree traversals systematically visit each node in a hierarchical structure exactly once.',
        'Depth-First Search (DFS) includes Pre-order (Root-Left-Right), In-order (Left-Root-Right), and Post-order (Left-Right-Root).',
        'In-order traversal of a Binary Search Tree (BST) produces strictly ascending sorted order.',
        'Breadth-First Search (BFS / Level Order) uses a FIFO Queue data structure with O(V + E) time complexity.',
      ],
      keyTerms: [
        {
          term: 'Binary Search Tree (BST)',
          definition: 'A binary tree where each node has at most two children, with left keys strictly smaller and right keys strictly greater than the root.',
          importance: 'high',
        },
        {
          term: 'In-order Traversal',
          definition: 'Recursive traversal pattern: Visit Left Subtree -> Visit Current Node -> Visit Right Subtree.',
          importance: 'high',
        },
        {
          term: 'Time Complexity (Traversal)',
          definition: 'O(N) where N is the total number of nodes, visiting each node exactly once.',
          importance: 'medium',
        },
        {
          term: 'Call Stack Height',
          definition: 'Determines space complexity: O(h) where h is tree height (O(log N) for balanced, O(N) for skewed trees).',
          importance: 'medium',
        },
      ],
      sections: [
        {
          heading: '1. Depth-First Traversal Variations',
          summary: 'Three fundamental orders to process nodes depending on when the current node is examined.',
          bulletPoints: [
            'Pre-order (NLR): Used to clone trees or serialize hierarchical representations.',
            'In-order (LNR): Crucial for BSTs to retrieve all elements in sorted order.',
            'Post-order (LRN): Used to delete or free tree nodes from leaves up to the root.',
          ],
          keyTakeaway: 'The name (Pre/In/Post) indicates where the ROOT node is visited relative to left and right children.',
        },
        {
          heading: '2. Breadth-First (Level-Order) Traversal',
          summary: 'Explores horizontal slices of the tree level by level starting from the root.',
          bulletPoints: [
            'Uses a Queue (FIFO) to track nodes on the frontier.',
            'Space complexity is proportional to the maximum width of the tree (up to N/2 nodes at leaf level).',
            'Essential for finding shortest path in unweighted graphs.',
          ],
          keyTakeaway: 'Always initialize queue with root and loop while queue is not empty.',
        },
      ],
    },
    flashcards: [
      {
        id: 'fc-cs-1',
        topic: 'BST Traversal',
        question: 'Which traversal algorithm guarantees reading elements of a Binary Search Tree in sorted ascending order?',
        answer: 'In-order Traversal (Left -> Root -> Right).',
        hint: 'It processes left smaller values before the node itself.',
        confidence: 'mastered' as any,
      },
      {
        id: 'fc-cs-2',
        topic: 'Data Structures',
        question: 'What fundamental data structure is used to implement Level-Order (Breadth-First) traversal iteratively?',
        answer: 'A Queue (FIFO - First In, First Out).',
        hint: 'Contrast with the Stack used for DFS.',
        confidence: 'mastered' as any,
      },
      {
        id: 'fc-cs-3',
        topic: 'Space Complexity',
        question: 'What is the worst-case space complexity of recursive DFS on a degenerate (skewed) binary tree with N nodes?',
        answer: 'O(N) auxiliary space on the recursion call stack.',
        hint: 'A degenerate tree resembles a singly linked list.',
        confidence: 'medium',
      },
    ],
    quiz: {
      id: 'quiz-cs-201',
      title: 'Tree Algorithms Verification Quiz',
      totalQuestions: 3,
      passingScore: 66,
      questions: [
        {
          id: 'q-cs-1',
          topic: 'Traversal Sequence',
          question: 'Given a tree with Root 10, Left 5, Right 15. What is the Post-order traversal sequence?',
          options: ['10 -> 5 -> 15', '5 -> 15 -> 10', '5 -> 10 -> 15', '15 -> 10 -> 5'],
          correctIndex: 1,
          explanation: 'Post-order visits Left (5), then Right (15), then Root (10).',
        },
        {
          id: 'q-cs-2',
          topic: 'Serialization',
          question: 'Which traversal is most commonly used to serialize and recreate an exact clone of an arbitrary binary tree?',
          options: ['In-order', 'Pre-order with null markers', 'Post-order without markers', 'Reverse In-order'],
          correctIndex: 1,
          explanation: 'Pre-order records roots first, allowing top-down reconstruction when deserializing.',
        },
        {
          id: 'q-cs-3',
          topic: 'Time Complexity',
          question: 'What is the time complexity of performing an In-Order traversal on a balanced binary search tree of N nodes?',
          options: ['O(log N)', 'O(N)', 'O(N log N)', 'O(N^2)'],
          correctIndex: 1,
          explanation: 'Every node in the tree must be visited once, giving O(N) time complexity.',
        },
      ],
    },
    reel: {
      id: 'reel-cs-201',
      title: 'Master Binary Trees in 60 Seconds',
      durationSeconds: 60,
      visualStyle: 'mindmap',
      narrationScript: 'Think of a tree data structure like a family hierarchy. When traversing with Depth First Search, In-Order is your secret weapon for Binary Search Trees because it always outputs values from smallest to greatest. If you need to search level by level like ripples in water, throw a Queue at it and run Breadth First Search.',
      audioWaveform: [0.1, 0.3, 0.6, 0.8, 0.9, 0.7, 0.5, 0.8, 0.9, 0.95, 0.7, 0.6, 0.8, 0.85, 0.6, 0.4, 0.3, 0.2],
      chapters: [
        { id: 'c-cs-1', title: '01. Tree Topology', timestampSeconds: 0, subtitle: 'Root, branches, leaves, and parent-child hierarchy.' },
        { id: 'c-cs-2', title: '02. In-order Secret', timestampSeconds: 20, subtitle: 'Left-Root-Right yields perfectly sorted values on BSTs.' },
        { id: 'c-cs-3', title: '03. BFS vs DFS', timestampSeconds: 40, subtitle: 'Queue for horizontal levels vs Stack for deep descent.' },
      ],
    },
    knowledgeGap: {
      overallMastery: 85,
      weakestArea: 'Iterative Post-Order Traversal with 2 Stacks',
      strongestArea: 'In-order BST Properties',
      recommendedStudyOrder: ['Iterative DFS implementations', 'Tree diameter calculations'],
      topics: [
        {
          name: 'BST Properties & In-order Ordering',
          masteryPercentage: 96,
          status: 'mastered',
          questionsAttempted: 15,
          recommendedAction: 'Excellent mastery! No further immediate revision needed.',
        },
        {
          name: 'Breadth-First Search & Queues',
          masteryPercentage: 88,
          status: 'mastered',
          questionsAttempted: 10,
          recommendedAction: 'Strong grasp of queue logic and level tracking.',
        },
        {
          name: 'Iterative Traversal (Stack Simulation)',
          masteryPercentage: 71,
          status: 'improving',
          questionsAttempted: 8,
          recommendedAction: 'Practice implementing Post-Order using a single stack and previous node pointer.',
        },
      ],
    },
  },
  {
    id: 'hist-105',
    title: 'The Industrial Revolution & Modern Economy',
    subject: 'World History',
    subjectColor: 'from-amber-500/20 to-yellow-500/10 text-amber-400 border-amber-500/30',
    type: 'image',
    sourceFileName: 'Handwritten_Lecture_Notes_Unit_4.png',
    uploadDate: '3 days ago',
    estimatedStudyTimeMinutes: 10,
    progressPercentage: 42,
    summaryNotes: {
      title: 'Industrial Revolution Transformation Summary',
      readingTimeMinutes: 4,
      keyTakeaways: [
        'Originated in Great Britain during the mid-18th century due to abundant coal, iron, capital, and colonial trade networks.',
        'The steam engine (James Watt) decoupled mechanical power from watermills and animal labor.',
        'Rapid urbanization created new social classes: the industrial bourgeoisie and the industrial proletariat.',
        'Sparked major political and economic theories, including Adam Smith\'s free-market capitalism and Karl Marx\'s scientific socialism.',
      ],
      keyTerms: [
        {
          term: 'Urbanization',
          definition: 'Mass migration of populations from rural agricultural villages into rapidly growing industrial cities.',
          importance: 'high',
        },
        {
          term: 'James Watt Steam Engine (1776)',
          definition: 'Significantly improved efficiency of Newcomen engine by adding a separate condenser, enabling widespread factory automation.',
          importance: 'high',
        },
        {
          term: 'Proletariat',
          definition: 'The industrial working class who do not own the means of production and sell their labor for wages.',
          importance: 'medium',
        },
      ],
      sections: [
        {
          heading: '1. Why Britain First?',
          summary: 'A convergence of geological, economic, and technological factors created the ideal cradle.',
          bulletPoints: [
            'Access to cheap, surface-level coal and iron ore deposits.',
            'High domestic wages encouraged business owners to substitute labor with machinery.',
            'Stable legal protections for patents, private property, and corporate charters.',
          ],
          keyTakeaway: 'Britain had the unique financial incentive to invent coal-powered machinery.',
        },
        {
          heading: '2. Social & Economic Upheaval',
          summary: 'The transition from domestic artisanal production to centralized factory systems.',
          bulletPoints: [
            '12 to 16 hour factory workdays under hazardous conditions with child labor.',
            'Rise of labor unions and legislative reforms such as the Factory Acts.',
            'Massive rise in total global productivity alongside soaring economic inequality.',
          ],
          keyTakeaway: 'Reshaped human society from rural agrarian rhythms to synchronized industrial shifts.',
        },
      ],
    },
    flashcards: [
      {
        id: 'fc-hist-1',
        topic: 'Inventions',
        question: 'Which critical innovation enabled factories to operate anywhere rather than being restricted to fast-flowing rivers?',
        answer: 'James Watt\'s improved rotary Steam Engine with a separate condenser.',
        hint: 'It ran on coal and generated rotary mechanical motion.',
        confidence: 'mastered' as any,
      },
      {
        id: 'fc-hist-2',
        topic: 'Demographics',
        question: 'What term describes the explosive movement of people from rural farmlands to crowded factory towns?',
        answer: 'Urbanization.',
        hint: 'Roots in the Latin word "urbs" for city.',
        confidence: 'medium',
      },
    ],
    quiz: {
      id: 'quiz-hist-105',
      title: 'Industrial Age Concepts Quiz',
      totalQuestions: 2,
      passingScore: 50,
      questions: [
        {
          id: 'q-hist-1',
          topic: 'British Advantages',
          question: 'Which geological resource gave Britain the decisive energy advantage during early industrialization?',
          options: ['Abundant Petroleum Oil', 'Large accessible Coal deposits', 'Uranium Ore', 'Natural Geothermal vents'],
          correctIndex: 1,
          explanation: 'Britain possessed easily extractable coal seams close to coastal and river shipping channels.',
        },
        {
          id: 'q-hist-2',
          topic: 'Social Impact',
          question: 'What were the Factory Acts passed in 19th-century Britain designed to address?',
          options: [
            'Prohibiting coal exports to Europe',
            'Regulating excessive working hours and child labor in textile mills',
            'Outlawing all steam-powered machinery',
            'Enforcing mandatory agricultural service for city workers',
          ],
          correctIndex: 1,
          explanation: 'The Factory Acts gradually curbed dangerous child labor and established daily hour limits.',
        },
      ],
    },
    reel: {
      id: 'reel-hist-105',
      title: 'How Steam Changed the World in 50 Seconds',
      durationSeconds: 50,
      visualStyle: 'motion-sketch',
      narrationScript: 'Before 1750, almost everything you touched was made by muscle or water wheels. Then came coal and steam. In the span of a single generation, pastoral Britain transformed into the workshop of the world. Trains shattered distance, factories churned out millions of goods, and humanity traded the sunrise for the factory whistle.',
      audioWaveform: [0.3, 0.5, 0.7, 0.85, 0.9, 0.6, 0.5, 0.7, 0.95, 0.8, 0.6, 0.7, 0.5, 0.4, 0.2],
      chapters: [
        { id: 'c-hist-1', title: '01. The Muscle Age', timestampSeconds: 0, subtitle: 'Human muscle and watermills before industrial power.' },
        { id: 'c-hist-2', title: '02. The Coal Spark', timestampSeconds: 18, subtitle: 'Steam engine unlocks exponential mechanical output.' },
        { id: 'c-hist-3', title: '03. Modern World Born', timestampSeconds: 35, subtitle: 'Urbanization, railroads, and the industrial clock.' },
      ],
    },
    knowledgeGap: {
      overallMastery: 42,
      weakestArea: 'Economic Theories (Smith vs Marx)',
      strongestArea: 'Invention Timelines',
      recommendedStudyOrder: ['Capitalism vs Socialism Origins', 'Factory Acts Legislation', 'Enclosure Acts Impact'],
      topics: [
        {
          name: 'Technological Inventions & Steam',
          masteryPercentage: 75,
          status: 'improving',
          questionsAttempted: 8,
          recommendedAction: 'Good grasp of Watt engine and spinning jenny mechanics.',
        },
        {
          name: 'Social Class Dynamics & Labor Reforms',
          masteryPercentage: 40,
          status: 'critical-gap',
          questionsAttempted: 5,
          recommendedAction: 'Study the specific provisions of the 1833 and 1847 Factory Acts.',
        },
        {
          name: 'Economic Doctrines & Political Reaction',
          masteryPercentage: 25,
          status: 'critical-gap',
          questionsAttempted: 4,
          recommendedAction: 'Compare Adam Smith Wealth of Nations with Marxist Das Kapital critiques.',
        },
      ],
    },
  },
]
